### ISSUE TITLE
Juno->VSCode maturity meta-issue

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1544]
This issue ties together all of the issues I opened on missing features from Juno that represented its maturity and were widely used around a lot of the Youtube videos and streams I could find.

- [ ] https://github.com/julia-vscode/julia-vscode/issues/1543
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1538
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1539
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1540
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1541
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1542
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1545
- [ ] https://github.com/julia-vscode/julia-vscode/issues/1547

Also, is there a way to change the default font and make it use Julia Mono or whatever that new font is? That default font is not great (as in, it has some weird artifacts in a few spots). I see that the most commonly used theme in VSCode is the Atom One Dark default theme extension, so 🤦 but that seems like something VSCode needs to fix on its end. An eventual JuliaPro on VSCode should probably be cognizant of this default theming issue, but that's a separate discussion. 

FWIW, I had been putting in feature requests to Juno since like the first day it went to Atom, so that was quite a tailored experience for people doing modeling and simulation, and those features seem to be the ones that have traditionally lagged in VSCode. However, these issues + inline evaluation of treeviews should cover most of it.

🥂 to a unified IDE future.

**Comment by ChrisRackauckas** [comment]
The other issue that popped up is that the text in VSCode has some anti-aliasing issues which makes it a bit more difficult to read than Atom. If anyone knows the upstream issue to track for that please link it.

**Comment by davidanthoff** [comment]
@ChrisRackauckas thanks so much for all the feedback, super helpful!

I'm going to close this issue: we don't use meta issues to track stuff in the repo here (other than the release planning). Best to just open individual issues per individual problem :)
