### ISSUE TITLE
Highlighting potential performance issues (tracker)

### ISSUE THREAD

**Issue by MilesCranmer** [julia-vscode/julia-vscode#3246]
I think a long term goal of the VSCode extension could be to use analysis tools to automatically highlight a range of potential performance problems in Julia code. The [Performance Tips](https://docs.julialang.org/en/v1/manual/performance-tips/) list is great --- I think many of these could (one day) be highlighted by the IDE, to lower friction for new users. If you have ever introduced a user to Julia, you will likely know that they immediately start introducing all kinds of performance issues like untyped global variables, abstract types, etc. Then, the user's code ends up being as slow as Python, and they wonder: "why bother with Julia when the performance is the same as Python, and Python as more libraries in [X]?". Of course, if they knew these performance issues earlier, they may have ended up with faster code and stuck with Julia.

Having the IDE point out performance issues immediately would make it a more pleasant experience and lower turnover of new users.

(Of course, one could find, install, and run an external package, like Cthulhu.jl or JET.jl. But for new users for whom we only have a 30-minute window to impress before they leave, it is not a great experience to have them go through this process. It's much more pleasant to have this executed automatically by VSCode. A tool chain becomes really amazing when you can use it to learn a language, just by reading the error/warning messages. Rust's VSCode extension is a great example of this!)

I wanted to make a checklist to track what performance tips are underlined by VSCode. Maintainers: feel free to edit as you like. Also feel free to link any existing issues (including completed ones) However, I should note that some of these points which might not be possible right now might well be possible in the future, so it is good to still track them. I'll also add some links at the bottom for relevant packages.

- [ ] [Performance critical code should be inside a function](https://docs.julialang.org/en/v1/manual/performance-tips/#Performance-critical-code-should-be-inside-a-function)
- [ ] [Avoid untyped global variables](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-untyped-global-variables)
- [ ] [Avoid fields with abstract type](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type)
- [ ] [Avoid containers with abstract type parameters](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-abstract-container)
- [ ] [Annotate values taken from untyped locations](https://docs.julialang.org/en/v1/manual/performance-tips/#Annotate-values-taken-from-untyped-locations)
- [ ] [Be aware of when Julia avoids specializing](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing)
- [ ] [Break functions into multiple definitions](https://docs.julialang.org/en/v1/manual/performance-tips/#Break-functions-into-multiple-definitions)
- [ ] [Write "type-stable" functions](https://docs.julialang.org/en/v1/manual/performance-tips/#Write-%22type-stable%22-functions)
- [ ] [Avoid changing the type of a variable](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-changing-the-type-of-a-variable)
- [ ] [Separate kernel functions (aka, function barriers)](https://docs.julialang.org/en/v1/manual/performance-tips/#kernel-functions)
- [ ] [Types with values-as-parameters](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-value-type)
- [ ] [Access arrays in memory order, along columns](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-column-major)
- [ ] [Pre-allocating outputs](https://docs.julialang.org/en/v1/manual/performance-tips/#Pre-allocating-outputs)
- [ ] [More dots: Fuse vectorized operations](https://docs.julialang.org/en/v1/manual/performance-tips/#More-dots:-Fuse-vectorized-operations)
- [ ] [Consider using views for slices](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-views)
- [ ] [Copying data is not always bad](https://docs.julialang.org/en/v1/manual/performance-tips/#Copying-data-is-not-always-bad)
- [ ] [Consider StaticArrays.jl for small fixed-size vector/matrix operations](https://docs.julialang.org/en/v1/manual/performance-tips/#Consider-StaticArrays.jl-for-small-fixed-size-vector/matrix-operations)
- [ ] [Avoid string interpolation for I/O](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-string-interpolation-for-I/O)
- [ ] [Optimize network I/O during parallel execution](https://docs.julialang.org/en/v1/manual/performance-tips/#Optimize-network-I/O-during-parallel-execution)
- [ ] [Avoid unnecessary arrays. For example, instead of sum([x,y,z]) use x+y+z.](https://docs.julialang.org/en/v1/manual/performance-tips/#Tweaks)
- [ ] [Use abs2(z) instead of abs(z)^2 for complex z. In general, try to rewrite code to use abs2 instead of abs for complex arguments.](https://docs.julialang.org/en/v1/manual/performance-tips/#Tweaks)
- [ ] [Use div(x,y) for truncating division of integers instead of trunc(x/y), fld(x,y) instead of floor(x/y), and cld(x,y) instead of ceil(x/y).](https://docs.julialang.org/en/v1/manual/performance-tips/#Tweaks)
- [ ] [Performance Annotations](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-annotations)
- [ ] [Treat Subnormal Numbers as Zeros](https://docs.julialang.org/en/v1/manual/performance-tips/#Treat-Subnormal-Numbers-as-Zeros)
- [ ] [Performance of captured variable](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-captured)

I think many of these could be opt-in warnings, especially if it is more ambiguous.

---

For several of these, I think @timholy's new Cthulhu.jl update could be used: https://discourse.julialang.org/t/ann-new-tools-for-fixing-performance-problems-in-julia/95773. e.g., See those red type annotations? I think eventually those could be indicated directly in VSCode based on, e.g., the current script's calls - and give a warning message to the user as a blue underline.

---

Let me know what you think. Thanks!
Miles
